---
title: "AFV Capstone Project"
author: "Kayla Shinevar"
date: "2023-07-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Alternative Fuel Vehicles Exploratory Data Analysis

In this data analytics project, I explore the landscape of alternative fuel vehicles (AFVs) in the United States using multiple datasets. By analyzing AFV registrations by state, alternative fuel/charging station availability, and various AFV models, I aim to gain insights into the adoption of alternative fuel vehicles and the growth of charging infrastructure. I hypothesize that states with a higher number of alternative fuel/charging stations will have a higher number of AFV registrations. Throughout the analysis, I leverage SQL for data processing and Tableau for visualization, providing clear and interactive representations of the data trends and relationships. This project showcases my proficiency in SQL and Tableau while investigating an essential aspect of sustainable transportation.

## Process

Below is a detailed step by step of my process used to complete this analysis.

### 1. Gather Data

In order to begin my project, I needed to find some datasets on Alternative Fuel Vehicles. I was able to find several easily downloadable datasets from the Alternative Fuels Data Center website. (https://afdc.energy.gov/)

I used the Alternative Fuel Stations, Laws and Incentives, Light Duty Vehicles, and Medium and Heavy Duty Vehicles datasets for this project

I also found a great table on the same website containing vehicle registration counts by state and fuel type [here](https://afdc.energy.gov/vehicle-registration). They have this table for the years 2016-2022.

Unfortunately, there was not a downloadable version of these tables so I needed to scrape it using rSelenium and rvest. I detailed my web scraping process in the document [Data_Scraping_Process.R](https://github.com/kaylaashine/AFV_Capstone/blob/main/Data_Scraping_Process.R) because it is very lengthy, but at the end of my web scraping, I had seven tables for each year from 2016-2022 detailing vehicle registrations by fuel type and state.

